### ISSUE TITLE
Поправить навигацию

### ISSUE THREAD

**Issue by IgorSamohin** [IgorSamohin/mental-care-by-marusia#11]
### TODO (может обновляться в процессе)
- [x] Убрать знаки пунктуации
- [x] Настроить все управляющие фразы (сделать их как можно короче и яснее)
- [x] Добавить обработку ошибок (фраз, которые ни подо что не подошли и в целом о ошибок всякого другого рода)
- [x] Решить проблему зацикливания на одной фразе
---
### Не приоритетно в данный момент
- [ ] Возможно, стоит сделать сравнение не на equals, а на совпадение в процентном соотношении. Также стоит разбить все команды на токены

**Comment by IlyaAAAA** [comment]
я могу начать это делать
