### ISSUE TITLE
Настроить виджеты

### ISSUE THREAD

**Issue by IgorSamohin** [IgorSamohin/mental-care-by-marusia#12]
### TODO (может обновляться в процессе)
- [x] Сделать музыкальный плеер
- [x] Сделать необходимые виджеты
- [ ] Прикрутить виджеты к состояниям, требующим виджеты (список даст @IlyaAAAA)
- [x] Сделать хранилище контента для виджетов (чтобы контент цеплялся сам рандомно)

**Comment by IgorSamohin** [comment]
Виджеты не поддерживаются Марусей в полной мере
