### ISSUE TITLE
Улучшить ответы Маруси 

### ISSUE THREAD

**Issue by IgorSamohin** [IgorSamohin/mental-care-by-marusia#13]
### TODO (может обновляться в процессе)
- [x] Проработать tts и text, чтобы текста, произносимого Марусей, было как можно меньше, а текст на экране был как можно более емким.
- [x] Расставить ударения и логические паузы в tts
- [x] Выдать @IgorSamohin список ответов, к которым прилагаются виджеты с картинками/музыкой и подобным
